doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: "%kernel.debug%"

        types:
            role_enum: App\Doctrine\Type\RoleEnumType
            type_complement_enum: App\Doctrine\Type\TypeComplementEnumType
            etat_commande_enum: App\Doctrine\Type\EtatCommandeEnumType
            type_livraison_enum: App\Doctrine\Type\TypeLivraisonEnumType
            type_article_enum: App\Doctrine\Type\TypeArticleEnumType
            methode_paiement_enum: App\Doctrine\Type\MethodePaiementEnumType
            statut_paiement_enum: App\Doctrine\Type\StatutPaiementEnumType
            text_array: App\Doctrine\Type\TextArrayType
    orm:
        validate_xml_mapping: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: "%kernel.project_dir%/src/Entity"
                prefix: 'App\Entity'
                alias: App
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
